# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'editor.ui'
## (Modified to make Trigger Logic SHARED between Triggers and Interactables)
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QFormLayout, QFrame, QGraphicsView, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QMenu, QMenuBar,
    QPushButton, QScrollArea, QSizePolicy, QSpinBox,
    QSplitter, QStackedWidget, QStatusBar, QTextEdit,
    QVBoxLayout, QWidget)

class Ui_LevelEditor(object):
    def setupUi(self, LevelEditor):
        if not LevelEditor.objectName():
            LevelEditor.setObjectName(u"LevelEditor")
        LevelEditor.resize(1280, 850)
        self.action_load_json = QAction(LevelEditor)
        self.action_load_json.setObjectName(u"action_load_json")
        self.action_save_json = QAction(LevelEditor)
        self.action_save_json.setObjectName(u"action_save_json")
        self.centralwidget = QWidget(LevelEditor)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.toolbox_container = QWidget(self.splitter)
        self.toolbox_container.setObjectName(u"toolbox_container")
        self.toolbox_container.setMinimumSize(QSize(340, 0))
        self.toolbox_container.setMaximumSize(QSize(16777215, 16777215))
        self.verticalLayout = QVBoxLayout(self.toolbox_container)
        self.verticalLayout.setObjectName(u"verticalLayout")
        
        self.group_tools = QGroupBox(self.toolbox_container)
        self.group_tools.setObjectName(u"group_tools")
        self.horizontalLayout_grid = QHBoxLayout(self.group_tools)
        self.horizontalLayout_grid.setObjectName(u"horizontalLayout_grid")
        self.chk_grid_snap = QCheckBox(self.group_tools)
        self.chk_grid_snap.setObjectName(u"chk_grid_snap")
        self.horizontalLayout_grid.addWidget(self.chk_grid_snap)
        self.label_grid = QLabel(self.group_tools)
        self.label_grid.setObjectName(u"label_grid")
        self.horizontalLayout_grid.addWidget(self.label_grid)
        self.spin_grid_size = QSpinBox(self.group_tools)
        self.spin_grid_size.setObjectName(u"spin_grid_size")
        self.spin_grid_size.setMinimum(1)
        self.spin_grid_size.setMaximum(512)
        self.spin_grid_size.setValue(32)
        self.horizontalLayout_grid.addWidget(self.spin_grid_size)
        self.verticalLayout.addWidget(self.group_tools)

        self.groupBox = QGroupBox(self.toolbox_container)
        self.groupBox.setObjectName(u"groupBox")
        self.verticalLayout_2 = QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.combo_zone_selector = QComboBox(self.groupBox)
        self.combo_zone_selector.setObjectName(u"combo_zone_selector")
        self.verticalLayout_2.addWidget(self.combo_zone_selector)
        self.line = QFrame(self.groupBox)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.verticalLayout_2.addWidget(self.line)
        self.list_objects = QListWidget(self.groupBox)
        self.list_objects.setObjectName(u"list_objects")
        self.verticalLayout_2.addWidget(self.list_objects)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.btn_add_object = QPushButton(self.groupBox)
        self.btn_add_object.setObjectName(u"btn_add_object")
        self.horizontalLayout_3.addWidget(self.btn_add_object)
        self.btn_delete_object = QPushButton(self.groupBox)
        self.btn_delete_object.setObjectName(u"btn_delete_object")
        self.horizontalLayout_3.addWidget(self.btn_delete_object)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)

        self.scrollArea = QScrollArea(self.toolbox_container)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 378, 800))
        self.verticalLayout_4 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.properties_box = QGroupBox(self.scrollAreaWidgetContents)
        self.properties_box.setObjectName(u"properties_box")
        self.formLayout = QFormLayout(self.properties_box)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.label = QLabel(self.properties_box)
        self.label.setObjectName(u"label")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.label)
        self.prop_id = QLineEdit(self.properties_box)
        self.prop_id.setObjectName(u"prop_id")
        self.prop_id.setReadOnly(True)
        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.prop_id)
        self.label_6 = QLabel(self.properties_box)
        self.label_6.setObjectName(u"label_6")
        
        self.prop_type = QComboBox(self.properties_box)
        self.prop_type.addItem("") # Obstacle
        self.prop_type.addItem("") # Interactable
        self.prop_type.addItem("") # Trigger
        self.prop_type.setObjectName(u"prop_type")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.prop_type)

        self.label_7 = QLabel(self.properties_box)
        self.label_7.setObjectName(u"label_7")
        self.formLayout.setWidget(2, QFormLayout.ItemRole.LabelRole, self.label_7)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.prop_x = QSpinBox(self.properties_box)
        self.prop_x.setObjectName(u"prop_x")
        self.prop_x.setMinimum(-9999)
        self.prop_x.setMaximum(9999)
        self.horizontalLayout_4.addWidget(self.prop_x)
        self.prop_y = QSpinBox(self.properties_box)
        self.prop_y.setObjectName(u"prop_y")
        self.prop_y.setMinimum(-9999)
        self.prop_y.setMaximum(9999)
        self.horizontalLayout_4.addWidget(self.prop_y)
        self.formLayout.setLayout(2, QFormLayout.ItemRole.FieldRole, self.horizontalLayout_4)

        self.label_2 = QLabel(self.properties_box)
        self.label_2.setObjectName(u"label_2")
        self.formLayout.setWidget(3, QFormLayout.ItemRole.LabelRole, self.label_2)
        self.layout_img_path = QHBoxLayout()
        self.layout_img_path.setObjectName(u"layout_img_path")
        self.prop_image_path_combo = QComboBox(self.properties_box)
        self.prop_image_path_combo.setObjectName(u"prop_image_path_combo")
        self.prop_image_path_combo.setEditable(True)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_image_path_combo.sizePolicy().hasHeightForWidth())
        self.prop_image_path_combo.setSizePolicy(sizePolicy)
        self.layout_img_path.addWidget(self.prop_image_path_combo)
        self.btn_browse_image = QPushButton(self.properties_box)
        self.btn_browse_image.setObjectName(u"btn_browse_image")
        self.btn_browse_image.setMaximumWidth(30)
        self.layout_img_path.addWidget(self.btn_browse_image)
        self.formLayout.setLayout(3, QFormLayout.ItemRole.FieldRole, self.layout_img_path)

        self.label_12 = QLabel(self.properties_box)
        self.label_12.setObjectName(u"label_12")
        self.formLayout.setWidget(4, QFormLayout.ItemRole.LabelRole, self.label_12)
        self.prop_image_preview = QLabel(self.properties_box)
        self.prop_image_preview.setObjectName(u"prop_image_preview")
        self.prop_image_preview.setMinimumSize(QSize(0, 100))
        self.prop_image_preview.setStyleSheet(u"background-color: rgb(22, 22, 22);\nborder: 1px solid gray;")
        self.prop_image_preview.setAlignment(Qt.AlignCenter)
        self.formLayout.setWidget(4, QFormLayout.ItemRole.FieldRole, self.prop_image_preview)

        self.label_8 = QLabel(self.properties_box)
        self.label_8.setObjectName(u"label_8")
        self.formLayout.setWidget(5, QFormLayout.ItemRole.LabelRole, self.label_8)
        self.prop_resize_factor = QDoubleSpinBox(self.properties_box)
        self.prop_resize_factor.setObjectName(u"prop_resize_factor")
        self.prop_resize_factor.setSingleStep(0.1)
        self.prop_resize_factor.setValue(4.0)
        self.formLayout.setWidget(5, QFormLayout.ItemRole.FieldRole, self.prop_resize_factor)

        self.label_9 = QLabel(self.properties_box)
        self.label_9.setObjectName(u"label_9")
        self.formLayout.setWidget(6, QFormLayout.ItemRole.LabelRole, self.label_9)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.prop_is_passable = QCheckBox(self.properties_box)
        self.prop_is_passable.setObjectName(u"prop_is_passable")
        self.horizontalLayout_7.addWidget(self.prop_is_passable)
        self.prop_starts_hidden = QCheckBox(self.properties_box)
        self.prop_starts_hidden.setObjectName(u"prop_starts_hidden")
        self.horizontalLayout_7.addWidget(self.prop_starts_hidden)
        self.prop_is_ground = QCheckBox(self.properties_box)
        self.prop_is_ground.setObjectName(u"prop_is_ground")
        self.horizontalLayout_7.addWidget(self.prop_is_ground)
        self.formLayout.setLayout(6, QFormLayout.ItemRole.FieldRole, self.horizontalLayout_7)

        self.label_10 = QLabel(self.properties_box)
        self.label_10.setObjectName(u"label_10")
        self.formLayout.setWidget(7, QFormLayout.ItemRole.LabelRole, self.label_10)
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.prop_hitbox_dx = QSpinBox(self.properties_box)
        self.prop_hitbox_dx.setObjectName(u"prop_hitbox_dx")
        self.prop_hitbox_dx.setMinimum(-999)
        self.prop_hitbox_dx.setMaximum(999)
        self.horizontalLayout_6.addWidget(self.prop_hitbox_dx)
        self.prop_hitbox_dy = QSpinBox(self.properties_box)
        self.prop_hitbox_dy.setObjectName(u"prop_hitbox_dy")
        self.prop_hitbox_dy.setMinimum(-999)
        self.prop_hitbox_dy.setMaximum(999)
        self.horizontalLayout_6.addWidget(self.prop_hitbox_dy)
        self.prop_hitbox_dw = QSpinBox(self.properties_box)
        self.prop_hitbox_dw.setObjectName(u"prop_hitbox_dw")
        self.prop_hitbox_dw.setMinimum(-999)
        self.prop_hitbox_dw.setMaximum(999)
        self.horizontalLayout_6.addWidget(self.prop_hitbox_dw)
        self.prop_hitbox_dh = QSpinBox(self.properties_box)
        self.prop_hitbox_dh.setObjectName(u"prop_hitbox_dh")
        self.prop_hitbox_dh.setMinimum(-999)
        self.prop_hitbox_dh.setMaximum(999)
        self.horizontalLayout_6.addWidget(self.prop_hitbox_dh)
        self.formLayout.setLayout(7, QFormLayout.ItemRole.FieldRole, self.horizontalLayout_6)
        
        self.label_z = QLabel(self.properties_box)
        self.label_z.setObjectName(u"label_z")
        self.formLayout.setWidget(8, QFormLayout.ItemRole.LabelRole, self.label_z)
        self.prop_z_index = QSpinBox(self.properties_box)
        self.prop_z_index.setObjectName(u"prop_z_index")
        self.prop_z_index.setMinimum(-100)
        self.prop_z_index.setMaximum(100)
        self.formLayout.setWidget(8, QFormLayout.ItemRole.FieldRole, self.prop_z_index)
        self.verticalLayout_4.addWidget(self.properties_box)

        self.group_animation = QGroupBox(self.scrollAreaWidgetContents)
        self.group_animation.setObjectName(u"group_animation")
        self.verticalLayout_5 = QVBoxLayout(self.group_animation)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.prop_anim_list = QListWidget(self.group_animation)
        self.prop_anim_list.setObjectName(u"prop_anim_list")
        self.verticalLayout_5.addWidget(self.prop_anim_list)
        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.btn_anim_add = QPushButton(self.group_animation)
        self.btn_anim_add.setObjectName(u"btn_anim_add")
        self.horizontalLayout_9.addWidget(self.btn_anim_add)
        self.btn_anim_remove = QPushButton(self.group_animation)
        self.btn_anim_remove.setObjectName(u"btn_anim_remove")
        self.horizontalLayout_9.addWidget(self.btn_anim_remove)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.label_13 = QLabel(self.group_animation)
        self.label_13.setObjectName(u"label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.prop_anim_speed = QDoubleSpinBox(self.group_animation)
        self.prop_anim_speed.setObjectName(u"prop_anim_speed")
        self.prop_anim_speed.setDecimals(3)
        self.prop_anim_speed.setSingleStep(0.01)
        self.prop_anim_speed.setValue(0.1)
        self.horizontalLayout_10.addWidget(self.prop_anim_speed)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4.addWidget(self.group_animation)

        # --- GRUPO INTERACCIÓN (Lógica Avanzada) ---
        self.group_interaction = QGroupBox(self.scrollAreaWidgetContents)
        self.group_interaction.setObjectName(u"group_interaction")
        self.group_interaction.setTitle("Lógica e Interacción")
        self.formLayout_2 = QFormLayout(self.group_interaction)
        self.formLayout_2.setObjectName(u"formLayout_2")

        # Stack para detalles visuales (Nota, Imagen) - Solo para Interactables
        self.prop_main_stack = QStackedWidget(self.group_interaction)
        self.prop_main_stack.setObjectName(u"prop_main_stack")
        
        # PAGINA 0: Interactable (Detalles Visuales)
        self.page_interactable = QWidget()
        self.layout_interactable = QFormLayout(self.page_interactable)
        
        self.lbl_int_type = QLabel("Tipo Visual:")
        self.prop_interaction_type = QComboBox()
        self.prop_interaction_type.addItems(["None", "Note", "Image", "Door"])
        self.layout_interactable.addRow(self.lbl_int_type, self.prop_interaction_type)
        
        self.lbl_flash = QLabel("Flash Image:")
        self.layout_flash = QHBoxLayout()
        self.prop_flash_image_path_combo = QComboBox()
        self.prop_flash_image_path_combo.setEditable(True)
        self.prop_flash_image_path_combo.setSizePolicy(sizePolicy)
        self.btn_browse_flash = QPushButton("...")
        self.btn_browse_flash.setMaximumWidth(30)
        self.layout_flash.addWidget(self.prop_flash_image_path_combo)
        self.layout_flash.addWidget(self.btn_browse_flash)
        self.layout_interactable.addRow(self.lbl_flash, self.layout_flash)
        
        self.lbl_data = QLabel("Datos Visuales:")
        self.prop_interaction_data_stack = QStackedWidget()
        
        # Sub-Stack Nota
        self.stack_page_note = QWidget()
        self.v_note = QVBoxLayout(self.stack_page_note)
        self.data_note_text = QTextEdit()
        self.v_note.addWidget(self.data_note_text)
        self.prop_interaction_data_stack.addWidget(self.stack_page_note)
        
        # Sub-Stack Imagen
        self.stack_page_image = QWidget()
        self.h_image = QHBoxLayout(self.stack_page_image)
        self.data_image_path_combo = QComboBox()
        self.data_image_path_combo.setEditable(True)
        self.data_image_path_combo.setSizePolicy(sizePolicy)
        self.btn_browse_data = QPushButton("...")
        self.btn_browse_data.setMaximumWidth(30)
        self.h_image.addWidget(self.data_image_path_combo)
        self.h_image.addWidget(self.btn_browse_data)
        self.prop_interaction_data_stack.addWidget(self.stack_page_image)
        
        # Sub-Stack Puerta
        self.stack_page_door = QWidget()
        self.prop_interaction_data_stack.addWidget(self.stack_page_door)
        
        self.layout_interactable.addRow(self.lbl_data, self.prop_interaction_data_stack)
        self.prop_main_stack.addWidget(self.page_interactable)

        # PAGINA 1: Trigger Puro (Vacía, ya que los controles ahora son compartidos abajo)
        self.page_trigger = QWidget()
        self.prop_main_stack.addWidget(self.page_trigger)

        # Añadir el stack al layout principal del grupo
        self.formLayout_2.setWidget(0, QFormLayout.SpanningRole, self.prop_main_stack)
        
        # --- SECCIÓN COMPARTIDA: LÓGICA DE EVENTOS ---
        # Estos controles ahora aparecen tanto para Triggers como para Interactuables
        
        self.line_logic = QFrame()
        self.line_logic.setFrameShape(QFrame.HLine)
        self.line_logic.setFrameShadow(QFrame.Sunken)
        self.formLayout_2.setWidget(1, QFormLayout.SpanningRole, self.line_logic)

        self.lbl_trig_cond = QLabel("Condición (Trigger):")
        self.prop_trigger_condition = QComboBox()
        self.prop_trigger_condition.addItems(["OnEnter", "OnInteract", "AutoStart", "IfFlag"])
        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.lbl_trig_cond)
        self.formLayout_2.setWidget(2, QFormLayout.FieldRole, self.prop_trigger_condition)
        
        self.lbl_trig_act = QLabel("Acción (Evento):")
        self.prop_trigger_action = QComboBox()
        self.prop_trigger_action.addItems(["SetFlag", "Teleport", "PlaySound", "UnhideObject", "ShowDialogue", "IncrementFlag"])
        self.formLayout_2.setWidget(3, QFormLayout.LabelRole, self.lbl_trig_act)
        self.formLayout_2.setWidget(3, QFormLayout.FieldRole, self.prop_trigger_action)
        
        self.lbl_trig_params = QLabel("Parámetros:\n(clave=valor)")
        self.prop_trigger_params = QTextEdit()
        self.prop_trigger_params.setPlaceholderText("ej: flag=puerta_abierta; value=true")
        self.prop_trigger_params.setMaximumHeight(80)
        self.formLayout_2.setWidget(4, QFormLayout.LabelRole, self.lbl_trig_params)
        self.formLayout_2.setWidget(4, QFormLayout.FieldRole, self.prop_trigger_params)
        
        # -------------------------------------------

        self.verticalLayout_4.addWidget(self.group_interaction)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.splitter.addWidget(self.toolbox_container)
        self.canvas_view = QGraphicsView(self.splitter)
        self.canvas_view.setObjectName(u"canvas_view")
        self.splitter.addWidget(self.canvas_view)
        self.splitter.setStretchFactor(0, 0)
        self.splitter.setStretchFactor(1, 1)
        self.horizontalLayout.addWidget(self.splitter)

        LevelEditor.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(LevelEditor)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 21))
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        LevelEditor.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(LevelEditor)
        self.statusbar.setObjectName(u"statusbar")
        LevelEditor.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menuArchivo.addAction(self.action_load_json)
        self.menuArchivo.addAction(self.action_save_json)

        self.retranslateUi(LevelEditor)
        self.prop_main_stack.setCurrentIndex(0)
        self.prop_interaction_data_stack.setCurrentIndex(1)

        QMetaObject.connectSlotsByName(LevelEditor)

    def retranslateUi(self, LevelEditor):
        LevelEditor.setWindowTitle(QCoreApplication.translate("LevelEditor", u"Editor de Niveles de Oakhill", None))
        self.action_load_json.setText(QCoreApplication.translate("LevelEditor", u"Cargar JSON", None))
        self.action_save_json.setText(QCoreApplication.translate("LevelEditor", u"Guardar JSON", None))
        
        self.group_tools.setTitle("Herramientas")
        self.chk_grid_snap.setText("Snap Grid")
        self.label_grid.setText("Size:")
        
        self.groupBox.setTitle(QCoreApplication.translate("LevelEditor", u"Objetos", None))
        self.label_5.setText(QCoreApplication.translate("LevelEditor", u"Zona:", None))
        self.btn_add_object.setText(QCoreApplication.translate("LevelEditor", u"+ Añadir", None))
        self.btn_delete_object.setText(QCoreApplication.translate("LevelEditor", u"- Borrar", None))
        self.properties_box.setTitle(QCoreApplication.translate("LevelEditor", u"Propiedades Generales", None))
        self.label.setText(QCoreApplication.translate("LevelEditor", u"ID:", None))
        self.label_6.setText(QCoreApplication.translate("LevelEditor", u"Tipo Objeto:", None))
        self.prop_type.setItemText(0, QCoreApplication.translate("LevelEditor", u"Obstacle", None))
        self.prop_type.setItemText(1, QCoreApplication.translate("LevelEditor", u"Interactable", None))
        self.prop_type.setItemText(2, QCoreApplication.translate("LevelEditor", u"Trigger", None))

        self.label_7.setText(QCoreApplication.translate("LevelEditor", u"Posición:", None))
        self.label_2.setText(QCoreApplication.translate("LevelEditor", u"Image Path:", None))
        self.btn_browse_image.setText(QCoreApplication.translate("LevelEditor", u"...", None))
        self.label_12.setText(QCoreApplication.translate("LevelEditor", u"Preview:", None))
        self.label_8.setText(QCoreApplication.translate("LevelEditor", u"Resize:", None))
        self.label_9.setText(QCoreApplication.translate("LevelEditor", u"Opciones:", None))
        self.prop_is_passable.setText(QCoreApplication.translate("LevelEditor", u"Pasable", None))
        self.prop_starts_hidden.setText(QCoreApplication.translate("LevelEditor", u"Oculto", None))
        self.prop_is_ground.setText(QCoreApplication.translate("LevelEditor", u"Suelo", None))
        self.label_10.setText(QCoreApplication.translate("LevelEditor", u"Hitbox:", None))
        self.label_z.setText(QCoreApplication.translate("LevelEditor", u"Z-Index:", None))
        self.group_animation.setTitle(QCoreApplication.translate("LevelEditor", u"Animación", None))
        self.btn_anim_add.setText(QCoreApplication.translate("LevelEditor", u"+", None))
        self.btn_anim_remove.setText(QCoreApplication.translate("LevelEditor", u"-", None))
        self.label_13.setText(QCoreApplication.translate("LevelEditor", u"Speed:", None))
        self.menuArchivo.setTitle(QCoreApplication.translate("LevelEditor", u"Archivo", None))