# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'editor.ui'
## (Modified to make Trigger Logic SHARED between Triggers and Interactables)
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QFormLayout, QFrame, QGraphicsView, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QMenu, QMenuBar,
    QPushButton, QScrollArea, QSizePolicy, QSpinBox,
    QSplitter, QStackedWidget, QStatusBar, QTextEdit,
    QVBoxLayout, QWidget)

from src.Game_Enums import Actions, Conditions, ObjectTypes

class Ui_LevelEditor(object):
    def setupUi(self, LevelEditor):
        if not LevelEditor.objectName():
            LevelEditor.setObjectName(u"LevelEditor")
        LevelEditor.resize(1280, 850)
        self.action_new_map = QAction(LevelEditor)
        self.action_new_map.setObjectName(u"action_new_map")
        self.action_load_json = QAction(LevelEditor)
        self.action_load_json.setObjectName(u"action_load_json")
        self.action_save_json = QAction(LevelEditor)
        self.action_save_json.setObjectName(u"action_save_json")
        self.centralwidget = QWidget(LevelEditor)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.toolbox_container = QWidget(self.splitter)
        self.toolbox_container.setObjectName(u"toolbox_container")
        self.toolbox_container.setMinimumSize(QSize(340, 0))
        self.toolbox_container.setMaximumSize(QSize(16777215, 16777215))
        self.verticalLayout = QVBoxLayout(self.toolbox_container)
        self.verticalLayout.setObjectName(u"verticalLayout")
        
        self.group_tools = QGroupBox(self.toolbox_container)
        self.group_tools.setObjectName(u"group_tools")
        self.horizontalLayout_grid = QHBoxLayout(self.group_tools)
        self.horizontalLayout_grid.setObjectName(u"horizontalLayout_grid")
        self.label_map = QLabel("Mapa Ref:", self.group_tools)
        self.horizontalLayout_grid.addWidget(self.label_map)
        self.combo_map_select = QComboBox(self.group_tools)
        self.horizontalLayout_grid.addWidget(self.combo_map_select)
        line = QFrame()
        line.setFrameShape(QFrame.VLine)
        line.setFrameShadow(QFrame.Sunken)
        self.horizontalLayout_grid.addWidget(line)
        self.chk_grid_snap = QCheckBox(self.group_tools)
        self.chk_grid_snap.setObjectName(u"chk_grid_snap")
        self.horizontalLayout_grid.addWidget(self.chk_grid_snap)
        self.label_grid = QLabel(self.group_tools)
        self.label_grid.setObjectName(u"label_grid")
        self.horizontalLayout_grid.addWidget(self.label_grid)
        self.spin_grid_size = QSpinBox(self.group_tools)
        self.spin_grid_size.setObjectName(u"spin_grid_size")
        self.spin_grid_size.setMinimum(1)
        self.spin_grid_size.setMaximum(512)
        self.spin_grid_size.setValue(32)
        self.horizontalLayout_grid.addWidget(self.spin_grid_size)
        self.verticalLayout.addWidget(self.group_tools)

        self.groupBox = QGroupBox(self.toolbox_container)
        self.groupBox.setObjectName(u"groupBox")
        self.verticalLayout_2 = QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.combo_zone_selector = QComboBox(self.groupBox)
        self.combo_zone_selector.setObjectName(u"combo_zone_selector")
        self.verticalLayout_2.addWidget(self.combo_zone_selector)
        self.line = QFrame(self.groupBox)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.verticalLayout_2.addWidget(self.line)
        self.list_objects = QListWidget(self.groupBox)
        self.list_objects.setObjectName(u"list_objects")
        self.verticalLayout_2.addWidget(self.list_objects)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.btn_add_object = QPushButton(self.groupBox)
        self.btn_add_object.setObjectName(u"btn_add_object")
        self.horizontalLayout_3.addWidget(self.btn_add_object)
        self.btn_delete_object = QPushButton(self.groupBox)
        self.btn_delete_object.setObjectName(u"btn_delete_object")
        self.horizontalLayout_3.addWidget(self.btn_delete_object)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)

        self.scrollArea = QScrollArea(self.toolbox_container)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 378, 800))
        self.verticalLayout_4 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.properties_box = QGroupBox(self.scrollAreaWidgetContents)
        self.properties_box.setObjectName(u"properties_box")
        self.formLayout = QFormLayout(self.properties_box)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.label = QLabel(self.properties_box)
        self.label.setObjectName(u"label")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.label)
        self.prop_id = QLineEdit(self.properties_box)
        self.prop_id.setObjectName(u"prop_id")
        self.prop_id.setReadOnly(True)
        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.prop_id)
        self.label_6 = QLabel(self.properties_box)
        self.label_6.setObjectName(u"label_6")
        
        self.prop_type = QComboBox(self.properties_box)
        self.prop_type.addItems([
            ObjectTypes.OBSTACLE,
            ObjectTypes.MIRROR,
            ObjectTypes.INTERACTABLE,
            ObjectTypes.TRIGGER,
            ObjectTypes.PRIMITIVE
        ])
        self.prop_type.setObjectName(u"prop_type")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.prop_type)

        self.label_7 = QLabel(self.properties_box)
        self.label_7.setObjectName(u"label_7")
        self.formLayout.setWidget(2, QFormLayout.ItemRole.LabelRole, self.label_7)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.prop_x = QSpinBox(self.properties_box)
        self.prop_x.setObjectName(u"prop_x")
        self.prop_x.setMinimum(-9999)
        self.prop_x.setMaximum(9999)
        self.horizontalLayout_4.addWidget(self.prop_x)
        self.prop_y = QSpinBox(self.properties_box)
        self.prop_y.setObjectName(u"prop_y")
        self.prop_y.setMinimum(-9999)
        self.prop_y.setMaximum(9999)
        self.horizontalLayout_4.addWidget(self.prop_y)
        self.formLayout.setLayout(2, QFormLayout.ItemRole.FieldRole, self.horizontalLayout_4)

        self.label_2 = QLabel(self.properties_box)
        self.label_2.setObjectName(u"label_2")
        self.formLayout.setWidget(3, QFormLayout.ItemRole.LabelRole, self.label_2)
        self.layout_img_path = QHBoxLayout()
        self.layout_img_path.setObjectName(u"layout_img_path")
        self.prop_image_path_combo = QComboBox(self.properties_box)
        self.prop_image_path_combo.setObjectName(u"prop_image_path_combo")
        self.prop_image_path_combo.setEditable(True)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prop_image_path_combo.sizePolicy().hasHeightForWidth())
        self.prop_image_path_combo.setSizePolicy(sizePolicy)
        self.layout_img_path.addWidget(self.prop_image_path_combo)
        self.btn_browse_image = QPushButton(self.properties_box)
        self.btn_browse_image.setObjectName(u"btn_browse_image")
        self.btn_browse_image.setMaximumWidth(30)
        self.layout_img_path.addWidget(self.btn_browse_image)
        self.formLayout.setLayout(3, QFormLayout.ItemRole.FieldRole, self.layout_img_path)

        self.label_12 = QLabel(self.properties_box)
        self.label_12.setObjectName(u"label_12")
        self.formLayout.setWidget(4, QFormLayout.ItemRole.LabelRole, self.label_12)
        self.prop_image_preview = QLabel(self.properties_box)
        self.prop_image_preview.setObjectName(u"prop_image_preview")
        self.prop_image_preview.setMinimumSize(QSize(0, 100))
        self.prop_image_preview.setStyleSheet(u"background-color: rgb(22, 22, 22);\nborder: 1px solid gray;")
        self.prop_image_preview.setAlignment(Qt.AlignCenter)
        self.formLayout.setWidget(4, QFormLayout.ItemRole.FieldRole, self.prop_image_preview)

        self.label_8 = QLabel(self.properties_box)
        self.label_8.setObjectName(u"label_8")
        self.formLayout.setWidget(5, QFormLayout.ItemRole.LabelRole, self.label_8)
        self.prop_resize_factor = QDoubleSpinBox(self.properties_box)
        self.prop_resize_factor.setObjectName(u"prop_resize_factor")
        self.prop_resize_factor.setSingleStep(0.1)
        self.prop_resize_factor.setValue(4.0)
        self.formLayout.setWidget(5, QFormLayout.ItemRole.FieldRole, self.prop_resize_factor)

        self.label_9 = QLabel(self.properties_box)
        self.label_9.setObjectName(u"label_9")
        self.formLayout.setWidget(6, QFormLayout.ItemRole.LabelRole, self.label_9)
        self.horizontalLayout_7 = QHBoxLayout()
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.prop_is_passable = QCheckBox(self.properties_box)
        self.prop_is_passable.setObjectName(u"prop_is_passable")
        self.horizontalLayout_7.addWidget(self.prop_is_passable)
        self.prop_starts_hidden = QCheckBox(self.properties_box)
        self.prop_starts_hidden.setObjectName(u"prop_starts_hidden")
        self.horizontalLayout_7.addWidget(self.prop_starts_hidden)
        self.prop_is_ground = QCheckBox(self.properties_box)
        self.prop_is_ground.setObjectName(u"prop_is_ground")
        self.horizontalLayout_7.addWidget(self.prop_is_ground)
        self.formLayout.setLayout(6, QFormLayout.ItemRole.FieldRole, self.horizontalLayout_7)

        self.label_10 = QLabel(self.properties_box)
        self.label_10.setObjectName(u"label_10")
        self.formLayout.setWidget(7, QFormLayout.ItemRole.LabelRole, self.label_10)
        self.horizontalLayout_6 = QHBoxLayout()
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.prop_hitbox_dx = QSpinBox(self.properties_box)
        self.prop_hitbox_dx.setObjectName(u"prop_hitbox_dx")
        self.prop_hitbox_dx.setMinimum(-999)
        self.prop_hitbox_dx.setMaximum(999)
        self.horizontalLayout_6.addWidget(self.prop_hitbox_dx)
        self.prop_hitbox_dy = QSpinBox(self.properties_box)
        self.prop_hitbox_dy.setObjectName(u"prop_hitbox_dy")
        self.prop_hitbox_dy.setMinimum(-999)
        self.prop_hitbox_dy.setMaximum(999)
        self.horizontalLayout_6.addWidget(self.prop_hitbox_dy)
        self.prop_hitbox_dw = QSpinBox(self.properties_box)
        self.prop_hitbox_dw.setObjectName(u"prop_hitbox_dw")
        self.prop_hitbox_dw.setMinimum(-999)
        self.prop_hitbox_dw.setMaximum(999)
        self.horizontalLayout_6.addWidget(self.prop_hitbox_dw)
        self.prop_hitbox_dh = QSpinBox(self.properties_box)
        self.prop_hitbox_dh.setObjectName(u"prop_hitbox_dh")
        self.prop_hitbox_dh.setMinimum(-999)
        self.prop_hitbox_dh.setMaximum(999)
        self.horizontalLayout_6.addWidget(self.prop_hitbox_dh)
        self.formLayout.setLayout(7, QFormLayout.ItemRole.FieldRole, self.horizontalLayout_6)
        
        self.label_z = QLabel(self.properties_box)
        self.label_z.setObjectName(u"label_z")
        self.formLayout.setWidget(8, QFormLayout.ItemRole.LabelRole, self.label_z)
        self.prop_z_index = QSpinBox(self.properties_box)
        self.prop_z_index.setObjectName(u"prop_z_index")
        self.prop_z_index.setMinimum(-100)
        self.prop_z_index.setMaximum(100)
        self.formLayout.setWidget(8, QFormLayout.ItemRole.FieldRole, self.prop_z_index)
        self.verticalLayout_4.addWidget(self.properties_box)

        self.lbl_size = QLabel("Tamaño (W x H):", self.properties_box)
        self.formLayout.setWidget(9, QFormLayout.LabelRole, self.lbl_size)
        self.layout_size = QHBoxLayout()
        self.prop_width = QSpinBox(self.properties_box)
        self.prop_width.setMinimum(1)
        self.prop_width.setMaximum(9999)
        self.prop_width.setValue(50)
        self.prop_height = QSpinBox(self.properties_box)
        self.prop_height.setMinimum(1)
        self.prop_height.setMaximum(9999)
        self.prop_height.setValue(50)
        self.layout_size.addWidget(self.prop_width)
        self.layout_size.addWidget(self.prop_height)
        self.formLayout.setLayout(9, QFormLayout.FieldRole, self.layout_size)
        
        self.lbl_color = QLabel("Color (R, G, B):", self.properties_box)
        self.formLayout.setWidget(10, QFormLayout.LabelRole, self.lbl_color)
        self.layout_color = QHBoxLayout()
        self.prop_color_r = QSpinBox(self.properties_box)
        self.prop_color_r.setRange(0, 255)
        self.prop_color_g = QSpinBox(self.properties_box)
        self.prop_color_g.setRange(0, 255)
        self.prop_color_b = QSpinBox(self.properties_box)
        self.prop_color_b.setRange(0, 255)
        self.layout_color.addWidget(self.prop_color_r)
        self.layout_color.addWidget(self.prop_color_g)
        self.layout_color.addWidget(self.prop_color_b)
        self.formLayout.setLayout(10, QFormLayout.FieldRole, self.layout_color)

        self.lbl_border = QLabel("Grosor Borde (0=Sólido):", self.properties_box)
        self.formLayout.setWidget(11, QFormLayout.LabelRole, self.lbl_border)
        self.prop_border_width = QSpinBox(self.properties_box)
        self.prop_border_width.setMinimum(0)
        self.prop_border_width.setMaximum(100)
        self.prop_border_width.setValue(0)
        self.formLayout.setWidget(11, QFormLayout.FieldRole, self.prop_border_width)

        self.label_mirror_y = QLabel("Reflejo Y (Mirror):", self.properties_box)
        self.formLayout.setWidget(12, QFormLayout.LabelRole, self.label_mirror_y)
        self.prop_reflection_offset = QSpinBox(self.properties_box)
        self.prop_reflection_offset.setMinimum(-999)
        self.prop_reflection_offset.setMaximum(999)
        self.formLayout.setWidget(12, QFormLayout.FieldRole, self.prop_reflection_offset)

        self.group_animation = QGroupBox(self.scrollAreaWidgetContents)
        self.group_animation.setObjectName(u"group_animation")
        self.verticalLayout_5 = QVBoxLayout(self.group_animation)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.prop_anim_list = QListWidget(self.group_animation)
        self.prop_anim_list.setObjectName(u"prop_anim_list")
        self.verticalLayout_5.addWidget(self.prop_anim_list)
        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.btn_anim_add = QPushButton(self.group_animation)
        self.btn_anim_add.setObjectName(u"btn_anim_add")
        self.horizontalLayout_9.addWidget(self.btn_anim_add)
        self.btn_anim_remove = QPushButton(self.group_animation)
        self.btn_anim_remove.setObjectName(u"btn_anim_remove")
        self.horizontalLayout_9.addWidget(self.btn_anim_remove)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.label_13 = QLabel(self.group_animation)
        self.label_13.setObjectName(u"label_13")
        self.horizontalLayout_10.addWidget(self.label_13)
        self.prop_anim_speed = QDoubleSpinBox(self.group_animation)
        self.prop_anim_speed.setObjectName(u"prop_anim_speed")
        self.prop_anim_speed.setDecimals(3)
        self.prop_anim_speed.setSingleStep(0.01)
        self.prop_anim_speed.setValue(0.1)
        self.horizontalLayout_10.addWidget(self.prop_anim_speed)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4.addWidget(self.group_animation)

        self.group_interaction = QGroupBox(self.scrollAreaWidgetContents)
        self.group_interaction.setObjectName(u"group_interaction")
        self.group_interaction.setTitle("Lógica e Interacción")
        self.formLayout_2 = QFormLayout(self.group_interaction)

        # 1. Stack Visual (Interactables)
        self.prop_main_stack = QStackedWidget(self.group_interaction)
        
        self.page_interactable = QWidget()
        self.layout_interactable = QFormLayout(self.page_interactable)
        self.lbl_int_type = QLabel("Tipo Visual:")
        self.prop_interaction_type = QComboBox()
        self.prop_interaction_type.addItems(["None", "Note", "Image", "Door"])
        self.layout_interactable.addRow(self.lbl_int_type, self.prop_interaction_type)
        
        self.lbl_flash = QLabel("Flash Image:")
        self.layout_flash = QHBoxLayout()
        self.prop_flash_image_path_combo = QComboBox()
        self.prop_flash_image_path_combo.setEditable(True)
        self.prop_flash_image_path_combo.setSizePolicy(sizePolicy)
        self.btn_browse_flash = QPushButton("...")
        self.btn_browse_flash.setMaximumWidth(30)
        self.layout_flash.addWidget(self.prop_flash_image_path_combo)
        self.layout_flash.addWidget(self.btn_browse_flash)
        self.layout_interactable.addRow(self.lbl_flash, self.layout_flash)

        self.lbl_used = QLabel("Used Image (Opcional):")
        self.layout_used = QHBoxLayout()
        self.prop_used_image_path_combo = QComboBox()
        self.prop_used_image_path_combo.setEditable(True)
        self.prop_used_image_path_combo.setSizePolicy(sizePolicy)
        self.btn_browse_used = QPushButton("...")
        self.btn_browse_used.setMaximumWidth(30)
        self.layout_used.addWidget(self.prop_used_image_path_combo)
        self.layout_used.addWidget(self.btn_browse_used)
        self.layout_interactable.addRow(self.lbl_used, self.layout_used)

        self.lbl_duration = QLabel("Duración (Frames):")
        self.layout_duration = QHBoxLayout()
        self.prop_interaction_duration = QSpinBox()
        self.prop_interaction_duration.setMinimum(1)
        self.prop_interaction_duration.setMaximum(9999)
        self.prop_interaction_duration.setValue(60)
        self.layout_duration.addWidget(self.prop_interaction_duration)
        self.layout_interactable.addRow(self.lbl_duration, self.layout_duration)

        self.lbl_charge = QLabel("Sonido Carga (Loop):")
        self.layout_charge = QHBoxLayout()
        self.prop_charge_sound_combo = QComboBox()
        self.prop_charge_sound_combo.setEditable(True)
        self.btn_browse_charge = QPushButton("...")
        self.btn_browse_charge.setMaximumWidth(30)
        self.layout_charge.addWidget(self.prop_charge_sound_combo)
        self.layout_charge.addWidget(self.btn_browse_charge)
        self.layout_interactable.addRow(self.lbl_charge, self.layout_charge)

        self.lbl_data = QLabel("Datos Visuales:")
        self.prop_interaction_data_stack = QStackedWidget()
        self.stack_page_note = QWidget()
        self.v_note = QVBoxLayout(self.stack_page_note)
        self.data_note_text = QTextEdit()
        self.v_note.addWidget(self.data_note_text)
        self.prop_interaction_data_stack.addWidget(self.stack_page_note)
        self.stack_page_image = QWidget()
        self.h_image = QHBoxLayout(self.stack_page_image)
        self.data_image_path_combo = QComboBox()
        self.data_image_path_combo.setEditable(True)
        self.data_image_path_combo.setSizePolicy(sizePolicy)
        self.btn_browse_data = QPushButton("...")
        self.btn_browse_data.setMaximumWidth(30)
        self.h_image.addWidget(self.data_image_path_combo)
        self.h_image.addWidget(self.btn_browse_data)
        self.prop_interaction_data_stack.addWidget(self.stack_page_image)
        self.stack_page_door = QWidget()
        self.prop_interaction_data_stack.addWidget(self.stack_page_door)
        self.layout_interactable.addRow(self.lbl_data, self.prop_interaction_data_stack)
        
        self.prop_main_stack.addWidget(self.page_interactable)
        self.page_trigger = QWidget()
        self.prop_main_stack.addWidget(self.page_trigger)
        self.formLayout_2.setWidget(0, QFormLayout.SpanningRole, self.prop_main_stack)
        
        self.line_logic = QFrame()
        self.line_logic.setFrameShape(QFrame.HLine)
        self.line_logic.setFrameShadow(QFrame.Sunken)
        self.formLayout_2.setWidget(1, QFormLayout.SpanningRole, self.line_logic)

        self.lbl_trig_cond = QLabel("Condición Global:", self.group_interaction)
        self.prop_trigger_condition = QComboBox(self.group_interaction)
        self.prop_trigger_condition.addItems([
            Conditions.ON_ENTER,
            Conditions.ON_INTERACT,
            Conditions.AUTO_START,
            Conditions.IF_FLAG
        ])
        self.formLayout_2.setWidget(2, QFormLayout.LabelRole, self.lbl_trig_cond)
        self.formLayout_2.setWidget(2, QFormLayout.FieldRole, self.prop_trigger_condition)
        
        self.lbl_trig_act = QLabel("Acción Global:", self.group_interaction)
        self.prop_trigger_action = QComboBox()
        self.prop_trigger_action.addItems([
            Actions.SET_FLAG, Actions.INCREMENT_FLAG, Actions.TELEPORT,
            Actions.PLAY_SOUND, Actions.UNHIDE_OBJECT, Actions.SHOW_DIALOGUE,
            Actions.CHANGE_LEVEL, Actions.SHOW_NOTE, Actions.SHOW_IMAGE, Actions.CLOSE_IMAGE
        ])
        self.formLayout_2.setWidget(3, QFormLayout.LabelRole, self.lbl_trig_act)
        self.formLayout_2.setWidget(3, QFormLayout.FieldRole, self.prop_trigger_action)
        
        self.lbl_trig_params = QLabel("Params Globales:\n(blocking=true)", self.group_interaction)
        self.prop_trigger_params = QTextEdit() # Este es para el objeto principal
        self.prop_trigger_params.setMaximumHeight(60)
        self.formLayout_2.setWidget(4, QFormLayout.LabelRole, self.lbl_trig_params)
        self.formLayout_2.setWidget(4, QFormLayout.FieldRole, self.prop_trigger_params)

        self.lbl_sequence = QLabel("--- Secuencia de Pasos ---", self.group_interaction)
        self.lbl_sequence.setAlignment(Qt.AlignCenter)
        self.formLayout_2.setWidget(5, QFormLayout.SpanningRole, self.lbl_sequence)
        
        self.list_trigger_sequence = QListWidget(self.group_interaction)
        self.list_trigger_sequence.setMaximumHeight(100)
        self.formLayout_2.setWidget(6, QFormLayout.SpanningRole, self.list_trigger_sequence)
        
        self.layout_seq_btns = QHBoxLayout()
        self.btn_seq_add = QPushButton("+", self.group_interaction)
        self.btn_seq_remove = QPushButton("-", self.group_interaction)
        self.btn_seq_up = QPushButton("▲", self.group_interaction)
        self.btn_seq_down = QPushButton("▼", self.group_interaction)
        self.layout_seq_btns.addWidget(self.btn_seq_add)
        self.layout_seq_btns.addWidget(self.btn_seq_remove)
        self.layout_seq_btns.addWidget(self.btn_seq_up)
        self.layout_seq_btns.addWidget(self.btn_seq_down)
        self.formLayout_2.setLayout(7, QFormLayout.SpanningRole, self.layout_seq_btns) # <-- CORREGIDO: SpanningRole
        
        self.group_step_detail = QGroupBox("Editar Paso Seleccionado", self.group_interaction)
        self.layout_step = QFormLayout(self.group_step_detail)
        
        self.lbl_step_act = QLabel("Acción Paso:", self.group_step_detail)
        self.prop_step_action = QComboBox(self.group_step_detail)
        self.prop_step_action.addItems([
            Actions.WAIT, Actions.SET_FLAG, Actions.INCREMENT_FLAG, Actions.TELEPORT,
            Actions.PLAY_SOUND, Actions.PLAY_SOUND, Actions.UNHIDE_OBJECT, Actions.SHOW_DIALOGUE,
            Actions.CHANGE_LEVEL, Actions.SHOW_IMAGE, Actions.CLOSE_IMAGE, Actions.SHOW_NOTE
        ])
        self.layout_step.addRow(self.lbl_step_act, self.prop_step_action)
        
        self.lbl_step_params = QLabel("Params Paso:", self.group_step_detail)
        self.prop_step_params = QTextEdit(self.group_step_detail)
        self.prop_step_params.setPlaceholderText("time=2.0")
        self.prop_step_params.setMaximumHeight(50)
        self.layout_step.addRow(self.lbl_step_params, self.prop_step_params)
        
        self.formLayout_2.setWidget(8, QFormLayout.SpanningRole, self.group_step_detail)

        self.verticalLayout_4.addWidget(self.group_interaction)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.splitter.addWidget(self.toolbox_container)
        self.canvas_view = QGraphicsView(self.splitter)
        self.canvas_view.setObjectName(u"canvas_view")
        self.splitter.addWidget(self.canvas_view)
        self.splitter.setStretchFactor(0, 0)
        self.splitter.setStretchFactor(1, 1)
        self.horizontalLayout.addWidget(self.splitter)

        LevelEditor.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(LevelEditor)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 21))
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        LevelEditor.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(LevelEditor)
        self.statusbar.setObjectName(u"statusbar")
        LevelEditor.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menuArchivo.addAction(self.action_new_map)
        self.menuArchivo.addAction(self.action_load_json)
        self.menuArchivo.addAction(self.action_save_json)

        self.retranslateUi(LevelEditor)
        self.prop_main_stack.setCurrentIndex(0)
        self.prop_interaction_data_stack.setCurrentIndex(1)

        QMetaObject.connectSlotsByName(LevelEditor)

    def retranslateUi(self, LevelEditor):
        LevelEditor.setWindowTitle(QCoreApplication.translate("LevelEditor", u"Editor de Niveles de Oakhill", None))
        self.action_new_map.setText(QCoreApplication.translate("LevelEditor", u"Nuevo JSON (desde Mapa)", None))
        self.action_load_json.setText(QCoreApplication.translate("LevelEditor", u"Cargar JSON", None))
        self.action_save_json.setText(QCoreApplication.translate("LevelEditor", u"Guardar JSON", None))
        
        self.group_tools.setTitle("Herramientas")
        self.chk_grid_snap.setText("Snap Grid")
        self.label_grid.setText("Size:")
        
        self.groupBox.setTitle(QCoreApplication.translate("LevelEditor", u"Objetos", None))
        self.label_5.setText(QCoreApplication.translate("LevelEditor", u"Zona:", None))
        self.btn_add_object.setText(QCoreApplication.translate("LevelEditor", u"+ Añadir", None))
        self.btn_delete_object.setText(QCoreApplication.translate("LevelEditor", u"- Borrar", None))
        self.properties_box.setTitle(QCoreApplication.translate("LevelEditor", u"Propiedades Generales", None))
        self.label.setText(QCoreApplication.translate("LevelEditor", u"ID:", None))
        self.label_6.setText(QCoreApplication.translate("LevelEditor", u"Tipo Objeto:", None))
        self.prop_type.setItemText(0, QCoreApplication.translate("LevelEditor", u"Obstacle", None))
        self.prop_type.setItemText(1, QCoreApplication.translate("LevelEditor", u"Mirror", None))
        self.prop_type.setItemText(2, QCoreApplication.translate("LevelEditor", u"Interactable", None))
        self.prop_type.setItemText(3, QCoreApplication.translate("LevelEditor", u"Trigger", None))
        self.prop_type.setItemText(4, QCoreApplication.translate("LevelEditor", u"Primitive", None))

        self.label_7.setText(QCoreApplication.translate("LevelEditor", u"Posición:", None))
        self.label_2.setText(QCoreApplication.translate("LevelEditor", u"Image Path:", None))
        self.btn_browse_image.setText(QCoreApplication.translate("LevelEditor", u"...", None))
        self.label_12.setText(QCoreApplication.translate("LevelEditor", u"Preview:", None))
        self.label_8.setText(QCoreApplication.translate("LevelEditor", u"Resize:", None))
        self.label_9.setText(QCoreApplication.translate("LevelEditor", u"Opciones:", None))
        self.prop_is_passable.setText(QCoreApplication.translate("LevelEditor", u"Pasable", None))
        self.prop_starts_hidden.setText(QCoreApplication.translate("LevelEditor", u"Oculto", None))
        self.prop_is_ground.setText(QCoreApplication.translate("LevelEditor", u"Suelo", None))
        self.label_10.setText(QCoreApplication.translate("LevelEditor", u"Hitbox:", None))
        self.label_z.setText(QCoreApplication.translate("LevelEditor", u"Z-Index:", None))
        
        self.group_animation.setTitle(QCoreApplication.translate("LevelEditor", u"Animación", None))
        self.btn_anim_add.setText(QCoreApplication.translate("LevelEditor", u"+", None))
        self.btn_anim_remove.setText(QCoreApplication.translate("LevelEditor", u"-", None))
        self.label_13.setText(QCoreApplication.translate("LevelEditor", u"Speed:", None))
        
        self.group_interaction.setTitle(QCoreApplication.translate("LevelEditor", u"Configuración Específica", None))
        
        # --- NOMBRES CORREGIDOS AQUÍ ---
        self.lbl_int_type.setText(QCoreApplication.translate("LevelEditor", u"Tipo Visual:", None))
        self.prop_interaction_type.setItemText(0, QCoreApplication.translate("LevelEditor", u"None", None))
        self.prop_interaction_type.setItemText(1, QCoreApplication.translate("LevelEditor", u"Note", None))
        self.prop_interaction_type.setItemText(2, QCoreApplication.translate("LevelEditor", u"Image", None))
        self.prop_interaction_type.setItemText(3, QCoreApplication.translate("LevelEditor", u"Door", None))
        
        self.lbl_flash.setText(QCoreApplication.translate("LevelEditor", u"Flash Image:", None))
        self.btn_browse_flash.setText(QCoreApplication.translate("LevelEditor", u"...", None))
        
        self.lbl_used.setText(QCoreApplication.translate("LevelEditor", u"Used Image (Opcional):", None))
        self.btn_browse_used.setText(QCoreApplication.translate("LevelEditor", u"...", None))
        
        self.lbl_duration.setText(QCoreApplication.translate("LevelEditor", u"Duración (Frames):", None))
        
        self.lbl_charge.setText(QCoreApplication.translate("LevelEditor", u"Sonido Carga (Loop):", None))
        self.btn_browse_charge.setText(QCoreApplication.translate("LevelEditor", u"...", None))
        
        self.lbl_data.setText(QCoreApplication.translate("LevelEditor", u"Datos Visuales:", None))
        self.btn_browse_data.setText(QCoreApplication.translate("LevelEditor", u"...", None))
        
        self.lbl_trig_cond.setText(QCoreApplication.translate("LevelEditor", u"Condición Global:", None))
        self.lbl_trig_act.setText(QCoreApplication.translate("LevelEditor", u"Acción Global:", None))
        self.lbl_trig_params.setText(QCoreApplication.translate("LevelEditor", u"Params Globales:", None))
        
        self.lbl_sequence.setText(QCoreApplication.translate("LevelEditor", u"--- Secuencia de Pasos ---", None))
        self.group_step_detail.setTitle(QCoreApplication.translate("LevelEditor", u"Editar Paso Seleccionado", None))
        self.lbl_step_act.setText(QCoreApplication.translate("LevelEditor", u"Acción Paso:", None))
        self.lbl_step_params.setText(QCoreApplication.translate("LevelEditor", u"Params Paso:", None))
        
        self.menuArchivo.setTitle(QCoreApplication.translate("LevelEditor", u"Archivo", None))